# file: code Makefile
# project: "SHO ve výrobě"
# course: IMS
# authors: xmikul69, zpodes05
#   @ VUT FIT, Brno
# date: 2021
#

BINARY=ims
OUTPUT=model.out

all:
	g++ main.cpp -o $(BINARY) -lsimlib -lm

clean:
	rm $(BINARY) $(OUTPUT) | true
