# file: code Makefile
# project: "SHO ve výrobě"
# course: IMS
# authors: xmikul69, zpodes05
#   @ VUT FIT, Brno
# date: 2021
#

BINARY=ims

all:
	g++ -lsimlib main.c -o $(BINARY)

clean:
	rm $(BINARY)
